### ISSUE TITLE
Linux Build - No text displayed

### ISSUE THREAD

**Issue by crshrprt** [reillypascal/RSAlgorithmicVerb#4]
Thank you for this interesting plugin.

I noticed there were some updates lately and gave it a new try.

Compiling on Linux (Debian sid), after the updates I have unfortunately the same problem I reported [here](https://github.com/reillypascal/RSBrokenMedia/issues/2) for RSBrokenMedia.
Where Verdana font is not available in the system, it ends up with a plugin's GUI with no text displayed.

I tried compiling it, after commenting out [line 34](https://github.com/reillypascal/RSAlgorithmicVerb/blob/c065914ff9e4c9b8c8db30268c882ac29ccb3a7c/Source/GuiStyles.h#L34) in GuiStyles.h, and text is displayed correctly (it uses the JUCE's default).

**Comment by reillypascal** [comment]
Good to know - thanks! I removed that line for now, and I may look into embedding fonts down the line.
